services:
  orders-db:
    image: postgres:16
    container_name: orders-db

    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5437:5432"

    volumes:
      - order-db-data:/var/lib/postgresql/data

    networks:
      - microservices-net

  auth-service:
    container_name: order-service
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/orders_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVICES_USER_SERVICE_URL: http://order-service:8082

      JWT_SECRET: bXktc3VwZXItc2VjcmV0LWtleS1teS1zdXBlci1zZWNyZXQta2V5LTEyMzQ=

    networks:
      - microservices-net

    depends_on:
      - orders-db

volumes:
  auth-db-data:

networks:
  microservices-net:
    external: true