spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-check-sums: true
server:
  port: 8082

services:
  users-service:
    url: ${SERVICES_USERS_SERVICE_URL:http://users-service:8080}

logging:
  level:
    root: INFO
    org.springframework: INFO